[package]
name = "rt-poa"
version = "0.1.0"
edition = "2021"

[dependencies]
ruc = { version = "4.1.0", features = ["crypto"] }
vsdb_trie_map = "0.3.0"

rand = "0.8"
ed25519-zebra = { version = "3.1.0", features = ["serde"] }

bcs = "0.1.5"
serde = { version = "1.0", features = ["derive"] }
